spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guard_db?serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 8080